- name: Update package lists and install socat
  become: true
  ansible.builtin.apt:
    name: socat
    state: present
    update_cache: yes

- name: Create the acme user group
  become: true
  ansible.builtin.group:
    name: acme
    state: present

- name: Create a system user for the ACME client
  become: true
  ansible.builtin.user:
    state: present
    name: acme
    groups: acme,haproxy
    home: /var/lib/acme
    system: true

- name: Fetch acme shell script from Github repo
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/acmesh-official/acme.sh/refs/heads/master/acme.sh
    dest: /tmp/acme.sh
    mode: '0744'
    
- name: Run the acme script install step
  become: true
  ansible.builtin.command: 
    chdir: /tmp
    argv: 
      - /tmp/acme.sh 
      - --install 
      - --no-cron 
      - --no-profile 
      - --home 
      - /usr/local/share/acme.sh

- name: Symlink acme script to path
  become: true
  ansible.builtin.file:
    src: /usr/local/share/acme.sh/acme.sh
    dest: /usr/local/bin/acme
    mode: '0755'
    state: link

- name: Test using LE staging server
  become: true
  ansible.builtin.shell: acme --register-account --server letsencrypt_test -m kscott.mets@gmail.com > /tmp/account.out
