- name: Install prerequisites for apt over HTTPS
  become: true
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: Add k8s repo
  become: true
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: deb
    uris: https://pkgs.k8s.io/core:/stable:/v1.34/deb/
    suites: '/'
    architectures: amd64
    signed_by: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
  notify:
    - Update package lists

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl
    state: present

- name: Install kubelet
  ansible.builtin.apt:
    name: kubelet
    state: present

- name: Install kubeadm
  ansible.builtin.apt:
    name: kubeadm
    state: present

- name: Start and enable kubelet
  ansible.builtin.service:
    name: kubelet
    state: restarted
    enabled: true

- name: Add helm repo
  ansible.builtin.deb822_repository:
    name: helm
    types: deb
    uris: https://packages.buildkite.com/helm-linux/helm-debian/any/
    suites: "any"
    components: "main"
    architectures: amd64
    signed_by: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
